package view;


import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Juanl
 */
public class JurosSimplesSDI extends javax.swing.JFrame {
    int dt = 0;
    /**
     * Creates new form JurosSimplesSDI
     */
    public JurosSimplesSDI() {
        initComponents();
        lblCap.setVisible(false);
        txtCap.setVisible(false);
        
        txtJuros.setVisible(false);
        lblJuros.setVisible(false);
        
        lblTaxa.setVisible(false);
        txtTaxa.setVisible(false);
        
        lblTempo.setVisible(false);
        txtTempo.setVisible(false);
        
        jCTaxa.setVisible(false);
        
        jPResultado.setVisible(false);
        
        lblMontante.setVisible(false);
        jMontRes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPResultado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblMontante = new javax.swing.JLabel();
        jCapRes = new javax.swing.JLabel();
        jTaxaRes = new javax.swing.JLabel();
        jTempoRes = new javax.swing.JLabel();
        jJurosRes = new javax.swing.JLabel();
        jMontRes = new javax.swing.JLabel();
        btnMontante = new javax.swing.JButton();
        btnMontanteExplicado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCap = new javax.swing.JButton();
        btnTaxa = new javax.swing.JButton();
        btnJuros = new javax.swing.JButton();
        lblTaxa = new javax.swing.JLabel();
        lblJuros = new javax.swing.JLabel();
        txtCap = new javax.swing.JTextField();
        txtTaxa = new javax.swing.JTextField();
        txtTempo = new javax.swing.JTextField();
        lblCap = new javax.swing.JLabel();
        jCTaxa = new javax.swing.JComboBox<>();
        btnTempo = new javax.swing.JButton();
        txtJuros = new javax.swing.JTextField();
        lblTempo = new javax.swing.JLabel();
        btnCapExplicado = new javax.swing.JButton();
        btnJurosExplicado = new javax.swing.JButton();
        btnTempoExplicado = new javax.swing.JButton();
        btnTaxaExplicado = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculando"));

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel1.setText("Capital (C): ");

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel2.setText("Taxa (I): ");

        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel3.setText("Juros (J): ");

        jLabel10.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel10.setText("Tempo (t): ");

        lblMontante.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lblMontante.setText("Montante(S): ");

        jCapRes.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jCapRes.setText("Resultado");

        jTaxaRes.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jTaxaRes.setText("Resultado");

        jTempoRes.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jTempoRes.setText("Resultado");

        jJurosRes.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jJurosRes.setText("Resultado");

        jMontRes.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jMontRes.setText("Resultado");

        btnMontante.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        btnMontante.setText("Calcular Montante(S)");
        btnMontante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontanteActionPerformed(evt);
            }
        });

        btnMontanteExplicado.setBackground(new java.awt.Color(255, 255, 255));
        btnMontanteExplicado.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        btnMontanteExplicado.setText("?");
        btnMontanteExplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontanteExplicadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPResultadoLayout = new javax.swing.GroupLayout(jPResultado);
        jPResultado.setLayout(jPResultadoLayout);
        jPResultadoLayout.setHorizontalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(55, 55, 55))
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPResultadoLayout.createSequentialGroup()
                        .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(lblMontante))
                        .addGap(58, 58, 58)
                        .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTempoRes)
                            .addComponent(jMontRes)
                            .addComponent(jJurosRes)
                            .addGroup(jPResultadoLayout.createSequentialGroup()
                                .addComponent(jCapRes)
                                .addGap(128, 128, 128)
                                .addComponent(btnMontante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMontanteExplicado))
                            .addComponent(jTaxaRes))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPResultadoLayout.setVerticalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCapRes)
                    .addComponent(btnMontante)
                    .addComponent(btnMontanteExplicado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTaxaRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTempoRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jJurosRes))
                .addGap(11, 11, 11)
                .addGroup(jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontante)
                    .addComponent(jMontRes))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("O que você quer calcular?"));

        btnCap.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        btnCap.setText("Capital(C)");
        btnCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapActionPerformed(evt);
            }
        });

        btnTaxa.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        btnTaxa.setText("Taxa(I) ");
        btnTaxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaxaActionPerformed(evt);
            }
        });

        btnJuros.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        btnJuros.setText("Juros(J)");
        btnJuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJurosActionPerformed(evt);
            }
        });

        lblTaxa.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lblTaxa.setText("Taxa :");

        lblJuros.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lblJuros.setText("Juros :");

        txtCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapActionPerformed(evt);
            }
        });

        lblCap.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lblCap.setText("Capital: ");

        jCTaxa.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jCTaxa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Anos", "Meses", "Dias" }));
        jCTaxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTaxaActionPerformed(evt);
            }
        });

        btnTempo.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        btnTempo.setText("Tempo");
        btnTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempoActionPerformed(evt);
            }
        });

        lblTempo.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lblTempo.setText("Tempo");

        btnCapExplicado.setBackground(new java.awt.Color(255, 255, 255));
        btnCapExplicado.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        btnCapExplicado.setText("?");
        btnCapExplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapExplicadoActionPerformed(evt);
            }
        });

        btnJurosExplicado.setBackground(new java.awt.Color(255, 255, 255));
        btnJurosExplicado.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        btnJurosExplicado.setText("?");
        btnJurosExplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJurosExplicadoActionPerformed(evt);
            }
        });

        btnTempoExplicado.setBackground(new java.awt.Color(255, 255, 255));
        btnTempoExplicado.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        btnTempoExplicado.setText("?");
        btnTempoExplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempoExplicadoActionPerformed(evt);
            }
        });

        btnTaxaExplicado.setBackground(new java.awt.Color(255, 255, 255));
        btnTaxaExplicado.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        btnTaxaExplicado.setText("?");
        btnTaxaExplicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaxaExplicadoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapExplicado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnJuros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTaxa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTempoExplicado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnTaxaExplicado))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnJurosExplicado)))))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTaxa)
                    .addComponent(lblCap)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblJuros)
                        .addComponent(lblTempo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCap)
                    .addComponent(txtJuros)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTaxa, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTempo))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltar)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCap)
                    .addComponent(lblCap)
                    .addComponent(txtCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapExplicado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaxa)
                    .addComponent(lblTaxa)
                    .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaxaExplicado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTempo)
                    .addComponent(lblTempo)
                    .addComponent(btnTempoExplicado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJuros)
                    .addComponent(lblJuros)
                    .addComponent(btnJurosExplicado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapActionPerformed

    private void btnMontanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontanteActionPerformed
        jPResultado.setVisible(true);
        lblMontante.setVisible(true);
        jMontRes.setVisible(true);
        double j = parseDouble(jJurosRes.getText());
        double t = parseInt(jTempoRes.getText());
        double c = parseDouble(jCapRes.getText());
        double m = c + (j*t);
        
        jMontRes.setText(""+m);
        
        
    }//GEN-LAST:event_btnMontanteActionPerformed

    private void btnCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapActionPerformed
        dt =1;
        lblCap.setVisible(false);
        txtCap.setVisible(false);
        
        lblTaxa.setVisible(true);
        txtTaxa.setVisible(true);
        
        lblTempo.setVisible(true);
        txtTempo.setVisible(true);
        
        jCTaxa.setVisible(true);
        jCTaxa.setVisible(true);
        
        lblJuros.setVisible(true);
        txtJuros.setVisible(true);
    }//GEN-LAST:event_btnCapActionPerformed

    private void btnTaxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaxaActionPerformed
        dt = 2;
        lblCap.setVisible(true);
        txtCap.setVisible(true);
        
        lblTaxa.setVisible(false);
        txtTaxa.setVisible(false);
        
        lblTempo.setVisible(true);
        txtTempo.setVisible(true);
        
        jCTaxa.setVisible(false);
        jCTaxa.setVisible(false);
        
        lblJuros.setVisible(true);
        txtJuros.setVisible(true);
    }//GEN-LAST:event_btnTaxaActionPerformed

    private void btnTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempoActionPerformed
        dt = 3;
        
        lblCap.setVisible(true);
        txtCap.setVisible(true);
        
        lblTempo.setVisible(true);
        txtTempo.setVisible(true);
        
        lblTaxa.setVisible(true);
        txtTaxa.setVisible(true);
        
        lblTempo.setVisible(false);
        txtTempo.setVisible(false);
        
        jCTaxa.setVisible(true);
        jCTaxa.setVisible(true);
        
        lblJuros.setVisible(true);
        txtJuros.setVisible(true);
    }//GEN-LAST:event_btnTempoActionPerformed

    private void btnJurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJurosActionPerformed
        dt = 4;
        
         lblCap.setVisible(true);
        txtCap.setVisible(true);
        
        lblJuros.setVisible(true);
        txtJuros.setVisible(true);
        
        lblTaxa.setVisible(true);
        txtTaxa.setVisible(true);
        
        lblTempo.setVisible(true);
        txtTempo.setVisible(true);
        
        jCTaxa.setVisible(true);
        jCTaxa.setVisible(true);
        
        lblJuros.setVisible(false);
        txtJuros.setVisible(false);
    }//GEN-LAST:event_btnJurosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPResultado.setVisible(true);
        double j, c, i;
        int t;
        try{
            switch(dt){
                case 1:
                    j = parseDouble(txtJuros.getText());
                    i = parseDouble(txtTaxa.getText());
                    t = parseInt(txtTempo.getText());
                    j = j/100;
                    c = i * t * j * 2;
                    jCapRes.setText(""+c);
                    jTaxaRes.setText(""+i);
                    jTempoRes.setText(""+t);
                    jJurosRes.setText(""+j*100);
                    break;
                case 2:
                    j = parseDouble(txtJuros.getText());
                    t = parseInt(txtTempo.getText());
                    c = parseDouble(txtCap.getText());
                    j = j/100;
                    i = (c * t * j)/2;
                    jCapRes.setText(""+c);
                    jTaxaRes.setText(""+i);
                    jTempoRes.setText(""+t);
                    jJurosRes.setText(""+j*100);
                    break;
                case 3:
                    i = parseDouble(txtTaxa.getText());
                    j = parseDouble(txtJuros.getText());
                    c = parseDouble(txtCap.getText());
                    j = j/100;
                    t = (int) (c * i * j);
                    jCapRes.setText(""+c);
                    jTaxaRes.setText(""+i);
                    jTempoRes.setText(""+t);
                    jJurosRes.setText(""+j*100);
                    break;
                case 4:
                    i = parseDouble(txtTaxa.getText());
                    t = parseInt(txtTempo.getText());
                    c = parseDouble(txtCap.getText());
                    j = (c * i * t)/100;
                    jCapRes.setText(""+c);
                    jTaxaRes.setText(""+i);
                    jTempoRes.setText(""+t);
                    jJurosRes.setText(""+j);
                    break;
                    
            }
        }catch(NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Insira os valores corretamente e preencha todos os campos");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCapExplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapExplicadoActionPerformed
        JOptionPane.showMessageDialog(null, "O que é Capital? \n Capital ou Principal é valor de uma quantia em dinheiro “na data zero”, \n ou seja, no inicio de uma aplicação.");
    }//GEN-LAST:event_btnCapExplicadoActionPerformed

    private void btnTaxaExplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaxaExplicadoActionPerformed
        JOptionPane.showMessageDialog(null, "O que é taxa \n  A taxa de juros indica qual remuneração será paga ao dinheiro emprestado, \n para um determinado período."
                + " O cálculo da taxa de juros é responsável pela "
                + "\nobservação da rentabilidade de uma operação financeira, \n "
                + "sendo indispensável para a tomada de decisão de investimentos.");
    }//GEN-LAST:event_btnTaxaExplicadoActionPerformed

    private void btnTempoExplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempoExplicadoActionPerformed
        JOptionPane.showMessageDialog(null, "Sem boa definição, ainda...");
    }//GEN-LAST:event_btnTempoExplicadoActionPerformed

    private void btnJurosExplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJurosExplicadoActionPerformed
        JOptionPane.showMessageDialog(null, "O que são Juros? \n Juros é o rendimento que se obtém quando se empresta dinheiro por um determinado período. \n Os juros são para o credor (aquele que tem algo a receber) "
                + "\numa compensação pelo tempo que ficará sem utilizar o dinheiro emprestado.");
    }//GEN-LAST:event_btnJurosExplicadoActionPerformed

    private void jCTaxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTaxaActionPerformed

    }//GEN-LAST:event_jCTaxaActionPerformed

    private void btnMontanteExplicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontanteExplicadoActionPerformed
                JOptionPane.showMessageDialog(null, "O que é Montante? \n Montante é um termo utilizado para definir \n a quantidade de dinheiro que uma pessoa física ou jurídica possui,\n uma soma de Capitais");
    }//GEN-LAST:event_btnMontanteExplicadoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JurosSimplesSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JurosSimplesSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JurosSimplesSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JurosSimplesSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JurosSimplesSDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCap;
    private javax.swing.JButton btnCapExplicado;
    private javax.swing.JButton btnJuros;
    private javax.swing.JButton btnJurosExplicado;
    private javax.swing.JButton btnMontante;
    private javax.swing.JButton btnMontanteExplicado;
    private javax.swing.JButton btnTaxa;
    private javax.swing.JButton btnTaxaExplicado;
    private javax.swing.JButton btnTempo;
    private javax.swing.JButton btnTempoExplicado;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCTaxa;
    private javax.swing.JLabel jCapRes;
    private javax.swing.JLabel jJurosRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jMontRes;
    private javax.swing.JPanel jPResultado;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jTaxaRes;
    private javax.swing.JLabel jTempoRes;
    private javax.swing.JLabel lblCap;
    private javax.swing.JLabel lblJuros;
    private javax.swing.JLabel lblMontante;
    private javax.swing.JLabel lblTaxa;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JTextField txtCap;
    private javax.swing.JTextField txtJuros;
    private javax.swing.JTextField txtTaxa;
    private javax.swing.JTextField txtTempo;
    // End of variables declaration//GEN-END:variables
}
